### ISSUE TITLE
Invalid session crashes app

### ISSUE THREAD

**Issue by harunsmrkovic** [digime/digime-sdk-android#15]
When SDK fails to obtain a session, app crashes

Log before crash:
```
    16:16:15.074    a:18    jMXtdPGrKiRMi3fKHdoqyxoq3olmyp5f using tlEmQrYDCuDUqgLnK8L5FzzesyPWhNGi - ca-contract-request-successful: {sdkversion=undefined, appname=UBDI, appid=REMOVED, contractid=REMOVED, appstatus=2, transactiontype=pull}
```

Crash:
```
	16:16:39.316	AndroidRuntime	FATAL EXCEPTION: OkHttp Dispatcher
Process: com.mobileubdiapp, PID: 30431
java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()
	at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:156)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
	at me.digi.sdk.api.interceptors.DMERetryInterceptor.intercept(DMERetryInterceptor.kt:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
	at me.digi.sdk.api.interceptors.DMEDefaultHeaderAppender.intercept(DMEDefaultHeaderAppender.kt:25)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:136)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

Btw, this is 3.0.1 SDK

**Comment by harunsmrkovic** [comment]
This crash happens every time when user rejects the auth
