### ISSUE TITLE
SDK Crashing (unknown reproduction steps)

### ISSUE THREAD

**Issue by harunsmrkovic** [digime/digime-sdk-android#18]
We are receiving the following crash into our Play Store:

```java.lang.IllegalStateException: 
  at okhttp3.internal.connection.Transmitter.newExchange$okhttp (Transmitter.kt:156)
  at okhttp3.internal.connection.ConnectInterceptor.intercept (ConnectInterceptor.kt:35)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:112)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:87)
  at okhttp3.internal.cache.CacheInterceptor.intercept (CacheInterceptor.kt:82)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:112)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:87)
  at okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.kt:84)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:112)
  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.kt:71)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:112)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:87)
  at me.digi.sdk.api.interceptors.DMERetryInterceptor.intercept (DMERetryInterceptor.kt:41)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:112)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:87)
  at me.digi.sdk.api.interceptors.DMEDefaultHeaderAppender.intercept (DMEDefaultHeaderAppender.kt:25)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:112)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:87)
  at okhttp3.RealCall.getResponseWithInterceptorChain (RealCall.kt:184)
  at okhttp3.RealCall$AsyncCall.run (RealCall.kt:136)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
  at java.lang.Thread.run (Thread.java:798)```

Console is suggesting that another issue, discovered during pre-launch tests, could be related:

```
java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()
FATAL EXCEPTION: OkHttp Dispatcher
Process: com.mobileubdiapp, PID: 11919
java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()
  at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:156)
  at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
  at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
  at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
  at me.digi.sdk.api.interceptors.DMERetryInterceptor.intercept(DMERetryInterceptor.kt:41)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
  at me.digi.sdk.api.interceptors.DMEDefaultHeaderAppender.intercept(DMEDefaultHeaderAppender.kt:25)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
  at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
  at okhttp3.RealCall$AsyncCall.run(RealCall.kt:136)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
  at java.lang.Thread.run(Thread.java:761)
```

**Comment by olileung** [comment]
Hi @harunsmrkovic
Thanks for reporting this issue. I've checked with the Android team and they've reported that this has now been fixed and should be available in the forthcoming release.

We're planning on releasing the SDK at the end of this week / early next week. 

Hope this helps.
